### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by AndySharez** [blahgeek/rabbitink#3]
Hello There,

I came along your great repository, as I am on the search for a cheaper version of dasung's or boox mira pro's monitor.

I just have some questions:

1) You write "You may buy such products (screen + control board) at waveshare".
Which control board do you exactly mean?!
Is this the correct display:
https://www.waveshare.com/product/displays/e-paper/epaper-1/13.3inch-e-paper-hat.htm
Just asking as there are a few diff. 13.3 inch displays.

2) What linux did you use to set it up;
Do I need any additional software, besides virtual monitor software?

Thank you.

This is really a great project, and I appreciate your effort in finding a priceworthy solution regarding an e-ink monitor.

**Comment by blahgeek** [comment]
Hello, I'm glad that you are interested in this project. Wanting for "a cheaper version of dasung's" was exactly my motivation for this project :)

> Which control board do you exactly mean?! Is this the correct display:  https://www.waveshare.com/product/displays/e-paper/epaper-1/13.3inch-e-paper-hat.htm  Just asking as there are a few diff. 13.3 inch displays.

I believe it is. Though I myself bought mine from its Chinese e-commerce site page that have slightly different title (mine does not say anything about "for raspberry pi"), but the photo and model number looks exactly same as my tested model. Note that this project does not use the "for raspberry pi" interface, it only uses the USB interface.

> What linux did you use to set it up;

I have successfully ran it in Ubuntu 20.04, latest archlinux and latest gentoo, but all with X11 desktop (not wayland). I don't think choices of specific linux distribution matters.

> Do I need any additional software, besides virtual monitor software?

You need [rust toolchain](https://rustup.rs/) to build this. No other runtime dependencies are required.

"Virtual monitor" is also not a must. It's only useful when you want it as a secondary monitor. This project by itself simplify mirrors (part of) the desktop to the e-ink display. So you can start without "virtual monitor" and it would simply mirror your main screen.

**Comment by AndySharez** [comment]
> Hello, I'm glad that you are interested in this project. Wanting for "a cheaper version of dasung's" was exactly my motivation for this project :)
> 
> > Which control board do you exactly mean?! Is this the correct display:  https://www.waveshare.com/product/displays/e-paper/epaper-1/13.3inch-e-paper-hat.htm  Just asking as there are a few diff. 13.3 inch displays.
> 
> I believe it is. Though I myself bought mine from its Chinese e-commerce site page that have slightly different title (mine does not say anything about "for raspberry pi"), but the photo and model number looks exactly same as my tested model. Note that this project does not use the "for raspberry pi" interface, it only uses the USB interface.
> 
> > What linux did you use to set it up;
> 
> I have successfully ran it in Ubuntu 20.04, latest archlinux and latest gentoo, but all with X11 desktop (not wayland). I don't think choices of specific linux distribution matters.
> 
> > Do I need any additional software, besides virtual monitor software?
> 
> You need [rust toolchain](https://rustup.rs/) to build this. No other runtime dependencies are required.
> 
> "Virtual monitor" is also not a must. It's only useful when you want it as a secondary monitor. This project by itself simplify mirrors (part of) the desktop to the e-ink display. So you can start without "virtual monitor" and it would simply mirror your main screen.

Thank you so much for your reply!

Yes, I think the 13.3 inch e-paper HAT must be the one, you have used as well.

I compared the price from the chinese waveshare shop to the intl. one, and the chinese shop offers the display for $307 / 2190 yuan, whereas the intl. for $400.
Quite a difference here...

Would love to order from there, but that's not possible as you need to have a chinese phone nr. / qq or wechat.


When I get my hands on the display, I will try it with windows 10 & ubuntu 22.04 I think.


And yes, I will definitely use it as a 2nd monitor, for coding purposes.

That's the main reason I am adopting this.


Thanks again for your help & great resource,
Andy

**Comment by blahgeek** [comment]
no problem. 

> I compared the price from the chinese waveshare shop to the intl. one, and the chinese shop offers the display for $307 / 2190 yuan, whereas the intl. for $400. Quite a difference here...
> 
> Would love to order from there, but that's not possible as you need to have a chinese phone nr. / qq or wechat.

Yeah that surprises me as well..

I live in China so I may be able to help you on that if it’s not too much hassle. Email me at yikai at z1k.dev , if you need.
